uploads = []
outputs = []

[[generated]]
id = "s6jBf5IZMZ_yZDPS-qQju"
uri = "file://artifacts/xf-store/public/images/product-jogger-black.png"
type = "image"
title = "generated_image"

[[generated]]
id = "c8yEubxXAQmVPpy2RGEq8"
uri = "file://artifacts/xf-store/public/images/product-jogger-black-flat.png"
type = "image"
title = "generated_image"

[[generated]]
id = "SywItdmICPX23wFDcoTer"
uri = "file://artifacts/xf-store/public/images/product-jogger-grey.png"
type = "image"
title = "generated_image"

[[generated]]
id = "Ql3J3NB3COp-jnxHbeVEo"
uri = "file://artifacts/xf-store/public/images/product-jogger-grey-flat.png"
type = "image"
title = "generated_image"

[[generated]]
id = "rhpDLo2LMiw75055f9WBl"
uri = "file://artifacts/xf-store/public/images/product-jogger-white.png"
type = "image"
title = "generated_image"
